before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    ldflags: "-s -w -X main.version={{ .Version }} -X main.commitHash={{ .ShortCommit }} -X main.buildDate={{ .Date }}"
    flags:
      - -tags=gen
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
