structure:
    cmd:
        server: legostarter
    internal:
        app:
            simple: legoservice
        platform:
            .gitkeep: emptyfile
        common:
            .gitkeep: emptyfile
    pkg:
        .gitkeep: emptyfile
    static:
        .gitkeep: emptyfile
