name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --debug

#      - name: Lint
#        run: make lint

      - name: Test
        run: make test
